# Generated by Django 3.2.4 on 2022-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='usn',
            field=models.CharField(max_length=30),
        ),
    ]
