from django.shortcuts import render
from studentform.models import form
from django.http import HttpResponse
# Create your views here.
def pyreg(request):
    if request.method=="POST":
        print(request.POST)
        if request.POST['phone']==request.POST['phone_repeat'] and request.POST['email']==request.POST['email_repeat'] :
            form.objects.create(full_name=request.POST['full_name'],
                        gender=request.POST['gender'],
                        dob=request.POST['dob'], 
                        phone=request.POST['phone'], 
                        email=request.POST['email'],
                        ten_th=request.POST['ten_th'], 
                        puc=request.POST['puc'],
                        diploma=request.POST['diploma'], 
                        aggregate_12=request.POST['aggregate_12'], 
                        aggregate_diploma=request.POST['aggregate_diploma'], 
                        yop_12=request.POST['yop_12'], 
                        yop_diploma=request.POST['yop_diploma'], 
                        diploma_college=request.POST['diploma_college'], 
                        diploma_branch=request.POST['diploma_branch'], 
                        diploma_branch_other=request.POST['diploma_branch_other'], 
                        degree=request.POST['degree'], 
                        degree_branch=request.POST['degree_branch'], 
                        degree_branch_other=request.POST['degree_branch_other'], 
                        agreegate_degree=request.POST['agreegate_degree'], 
                        degree_yop=request.POST['degree_yop'], 
                        uni_name=request.POST['uni_name'], 
                        usn=request.POST['usn'], 
                        clg_name=request.POST['clg_name'], 
                        place_clg=request.POST['place_clg'], 
                        backlog=request.POST['backlog'], 
                        current_backlog=request.POST['current_backlog'], 
                        gap_in_degree=request.POST['gap_in_degree'], 
                        master=request.POST['master'], 
                        master_qualification=request.POST['master_qualification'], 
                        master_degree=request.POST['master_degree'], 
                        other_master_degree=request.POST['other_master_degree'], 
                        aggrigate_master=request.POST['aggrigate_master'], 
                        master_yop=request.POST['master_yop'], 
                        master_uni_name=request.POST['master_uni_name'], 
                        master_usn=request.POST['master_usn'], 
                        master_clg_name=request.POST['master_clg_name'], 
                        Master_clg_place=request.POST['Master_clg_place'], 
                        master_fail_clear=request.POST['master_fail_clear'], 
                        master_existing_backlog=request.POST['master_existing_backlog'], 
                        year_gap_master=request.POST['year_gap_master'], 
                        certificate=request.POST['certificate'], 
                        ready_to_relocate=request.POST['ready_to_relocate'], 
                        Location=request.POST.getlist('Location'), 
                        you_have_passport=request.POST['you_have_passport'],
                        you_have_pancard=request.POST['you_have_pancard'], 
                        you_have_adharcard=request.POST['you_have_adharcard'], 
                        aadhar_no=request.POST['aadhar_no'], 
                        father_name=request.POST['father_name'], 
                        house_no=request.POST['house_no'], 
                        street_no=request.POST['street_no'], 
                        area_name=request.POST['area_name'], 
                        pincode=request.POST['pincode'], 
                        city=request.POST['city'], 
                        state=request.POST['state'])
            return HttpResponse("your responce submit successfull")
    return render(request,"form.html")